<?php
get_header();
$lotery_draws = function_exists( 'lotery_get_open_draws' ) ? lotery_get_open_draws() : array();
$lotery_draw  = ! empty( $lotery_draws ) ? $lotery_draws[0] : null;
$tickets_page = function_exists( 'lotery_page_url' ) ? lotery_page_url( 'my-tickets', '/my-tickets/' ) : home_url( '/my-tickets/' );
$buy_page     = function_exists( 'lotery_page_url' ) ? lotery_page_url( 'buy-tickets', '/buy-tickets/' ) : home_url( '/buy-tickets/' );
$tickets_url  = is_user_logged_in() ? $tickets_page : wp_login_url( $tickets_page );
$buy_url      = is_user_logged_in() ? $buy_page : wp_login_url( $buy_page );
?>
<main>
	<section class="lotery-hero">
		<div class="lotery-container lotery-hero-grid">
			<div class="lotery-hero-copy">
				<p class="lotery-eyebrow lotery-eyebrow-light"><?php esc_html_e( 'PLAY WITH PURPOSE', 'lotery-tickets' ); ?></p>
				<h1><?php esc_html_e( 'Your lucky moment is closer than you think.', 'lotery-tickets' ); ?></h1>
				<p><?php esc_html_e( 'Choose your numbers, secure your ticket, and be part of the next exciting draw. Simple, transparent, and made for every player.', 'lotery-tickets' ); ?></p>
				<div class="lotery-hero-actions"><a class="lotery-button lotery-button-yellow" href="#latest-draw"><?php esc_html_e( 'Explore the draw', 'lotery-tickets' ); ?></a><a class="lotery-text-link" href="<?php echo esc_url( $tickets_url ); ?>"><?php esc_html_e( 'View my tickets', 'lotery-tickets' ); ?> <span aria-hidden="true">→</span></a></div>
				<div class="lotery-hero-trust"><span>✓</span> <?php esc_html_e( 'Secure payments', 'lotery-tickets' ); ?><span>✓</span> <?php esc_html_e( 'Verified draws', 'lotery-tickets' ); ?></div>
			</div>
			<div class="lotery-hero-art" aria-hidden="true"><div class="lotery-orbit lotery-orbit-one"></div><div class="lotery-orbit lotery-orbit-two"></div><div class="lotery-ticket-preview"><span class="lotery-ticket-star">✦</span><small><?php esc_html_e( 'NEXT DRAW', 'lotery-tickets' ); ?></small><strong>$<?php echo esc_html( $lotery_draw ? number_format_i18n( $lotery_draw->jackpot, 0 ) : '25,000' ); ?></strong><span><?php echo esc_html( $lotery_draw ? $lotery_draw->draw_date : __( 'Saturday · 8:00 PM', 'lotery-tickets' ) ); ?></span><div class="lotery-ticket-numbers"><b>04</b><b>11</b><b>19</b><b>27</b><b>36</b></div></div><span class="lotery-floating-ball ball-one">7</span><span class="lotery-floating-ball ball-two">23</span><span class="lotery-floating-ball ball-three">41</span></div>
		</div>
	</section>
	<section class="lotery-stats"><div class="lotery-container lotery-stats-grid"><div><strong>$<?php echo esc_html( $lotery_draw ? number_format_i18n( $lotery_draw->jackpot / 1000, 0 ) . 'K' : '25K' ); ?></strong><span><?php esc_html_e( 'next jackpot', 'lotery-tickets' ); ?></span></div><div><strong>100%</strong><span><?php esc_html_e( 'verified draws', 'lotery-tickets' ); ?></span></div><div><strong>24/7</strong><span><?php esc_html_e( 'ticket access', 'lotery-tickets' ); ?></span></div></div></section>
	<section class="lotery-section" id="latest-draw"><div class="lotery-container"><div class="lotery-section-heading"><div><p class="lotery-eyebrow"><?php esc_html_e( 'THE NEXT CHANCE', 'lotery-tickets' ); ?></p><h2><?php esc_html_e( 'Ready for your lucky numbers?', 'lotery-tickets' ); ?></h2></div><span class="lotery-countdown"><?php echo esc_html( $lotery_draw ? sprintf( __( 'Drawing %s', 'lotery-tickets' ), $lotery_draw->draw_date ) : __( 'Drawing soon', 'lotery-tickets' ) ); ?></span></div><div class="lotery-draw-card"><div><p><?php esc_html_e( 'JACKPOT PRIZE', 'lotery-tickets' ); ?></p><strong>$<?php echo esc_html( $lotery_draw ? number_format_i18n( $lotery_draw->jackpot, 2 ) : '25,000.00' ); ?></strong><span><?php echo esc_html( $lotery_draw ? $lotery_draw->title : __( 'Weekly demo draw', 'lotery-tickets' ) ); ?></span></div><div class="lotery-draw-date"><small><?php esc_html_e( 'DRAW DATE', 'lotery-tickets' ); ?></small><strong><?php echo esc_html( $lotery_draw ? wp_date( 'd', strtotime( $lotery_draw->draw_date ) ) : '—' ); ?> <span><?php echo esc_html( $lotery_draw ? strtoupper( wp_date( 'M', strtotime( $lotery_draw->draw_date ) ) ) : '—' ); ?><br><?php echo esc_html( $lotery_draw ? strtoupper( wp_date( 'l', strtotime( $lotery_draw->draw_date ) ) ) : '' ); ?></span></strong></div><a class="lotery-button" href="<?php echo esc_url( $buy_url ); ?>"><?php esc_html_e( 'Get your ticket', 'lotery-tickets' ); ?> →</a></div></div></section>
	<section class="lotery-section lotery-how"><div class="lotery-container"><div class="lotery-section-heading centered"><div><p class="lotery-eyebrow"><?php esc_html_e( 'HOW IT WORKS', 'lotery-tickets' ); ?></p><h2><?php esc_html_e( 'Three steps to your chance', 'lotery-tickets' ); ?></h2></div></div><div class="lotery-steps"><div><span>01</span><h3><?php esc_html_e( 'Pick your numbers', 'lotery-tickets' ); ?></h3><p><?php esc_html_e( 'Choose your favourite numbers or let us pick for you.', 'lotery-tickets' ); ?></p></div><div><span>02</span><h3><?php esc_html_e( 'Secure your ticket', 'lotery-tickets' ); ?></h3><p><?php esc_html_e( 'Complete payment safely and receive instant confirmation.', 'lotery-tickets' ); ?></p></div><div><span>03</span><h3><?php esc_html_e( 'Check the draw', 'lotery-tickets' ); ?></h3><p><?php esc_html_e( 'Your printable ticket is always available in your dashboard.', 'lotery-tickets' ); ?></p></div></div></div></section>
	<section class="lotery-cta"><div class="lotery-container"><div><p class="lotery-eyebrow lotery-eyebrow-light"><?php esc_html_e( 'YOUR NUMBERS. YOUR MOMENT.', 'lotery-tickets' ); ?></p><h2><?php esc_html_e( 'Don’t miss the next draw.', 'lotery-tickets' ); ?></h2></div><a class="lotery-button lotery-button-yellow" href="<?php echo esc_url( $tickets_url ); ?>"><?php esc_html_e( 'Start playing', 'lotery-tickets' ); ?> →</a></div></section>
</main>
<?php get_footer(); ?>
